/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author crist
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecera = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        panelAgregarLista = new javax.swing.JPanel();
        etiquetaAgregarLista = new javax.swing.JLabel();
        campoAgregarLista = new javax.swing.JTextField();
        btnAgregarLista = new javax.swing.JButton();
        panelRemoverLista = new javax.swing.JPanel();
        etiquetaRemoverLista = new javax.swing.JLabel();
        campoRemoverLista = new javax.swing.JTextField();
        btnRemoverLista = new javax.swing.JButton();
        panelLista = new javax.swing.JPanel();
        lista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabecera.setBackground(new java.awt.Color(204, 204, 204));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Añadir y remover en lista");

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        panelAgregarLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar a la lista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        panelAgregarLista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaAgregarLista.setText("Ingresa un elemento:");
        panelAgregarLista.add(etiquetaAgregarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 26, 230, 20));
        panelAgregarLista.add(campoAgregarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, -1));

        btnAgregarLista.setText("Agregar");
        panelAgregarLista.add(btnAgregarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        getContentPane().add(panelAgregarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 150));

        panelRemoverLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remover en la lista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        panelRemoverLista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaRemoverLista.setText("Ingresa un elemento para borrar:");
        panelRemoverLista.add(etiquetaRemoverLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, -1));

        campoRemoverLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRemoverListaActionPerformed(evt);
            }
        });
        panelRemoverLista.add(campoRemoverLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 60, 240, -1));

        btnRemoverLista.setText("Remover");
        panelRemoverLista.add(btnRemoverLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 100, 80, -1));

        getContentPane().add(panelRemoverLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 280, 150));

        panelLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        panelLista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista.setText("[...]");
        panelLista.add(lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        getContentPane().add(panelLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 580, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoRemoverListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRemoverListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRemoverListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarLista;
    public javax.swing.JButton btnRemoverLista;
    private javax.swing.JPanel cabecera;
    public javax.swing.JTextField campoAgregarLista;
    public javax.swing.JTextField campoRemoverLista;
    private javax.swing.JLabel etiquetaAgregarLista;
    private javax.swing.JLabel etiquetaRemoverLista;
    public javax.swing.JLabel lista;
    private javax.swing.JPanel panelAgregarLista;
    private javax.swing.JPanel panelLista;
    private javax.swing.JPanel panelRemoverLista;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
